home/urls.py
"""Contains the application’s url."""
from django.urls import path
from . import views

app_name = "home"

urlpatterns = [
    path("", views.home, name="index"),
    path("mentions/", views.mentions, name="mentions"),
    path("product/", views.search, name="search"),
    path("product/?page=<int:page>", views.search, name="search"),
]

purbeurre/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("", include("home.urls")),
    path("", include("substitute.urls")),
    path("", include("account.urls")),
    path("admin/", admin.site.urls),
]

substitute/urls.py
"""Contains the application’s url."""
from django.urls import path
from . import views

app_name = "substitute"

urlpatterns = [
    path("substitute/<int:product_id>", views.substitute, name="search-a-substitute"),
    path(
        "substitute/<int:product_id>/?page=<int:page>",
        views.substitute,
        name="search-a-substitute",
    ),
    path("detail/<int:product_id>/<int:substitute_id>/", views.detail, name="detail"),
    path("save/<int:product_id>/<int:substitute_id>/", views.save, name="save"),
    path(
        "detail_favoris/<int:product_id>/<int:substitute_id>/",
        views.detail_favoris,
        name="detail_favoris",
    ),
]

home/models.py
from django.db import models


class Category(models.Model):
    """ Product Categories """

    name = models.CharField(max_length=100, unique=True, verbose_name="Nom")

    class Meta:
        verbose_name = "Catégorie"

    def __str__(self):
        return self.name


class Product(models.Model):
    """ Product """

    name = models.CharField(max_length=100, unique=True, verbose_name="Nom du produit")
    category_id = models.ForeignKey(
        Category,
        related_name="category",
        verbose_name="Catégorie ID",
        on_delete=models.CASCADE,
    )

    nutriscore = models.CharField(max_length=1, verbose_name="Nutriscore")
    url = models.URLField(unique=True, verbose_name="URL")
    photo = models.URLField(verbose_name="Photo")
    ingredients = models.URLField(verbose_name="Ingredients", null=True)
    fat_100g = models.DecimalField(max_digits=4, decimal_places=2, null=True)
    sugars_100g = models.DecimalField(max_digits=4, decimal_places=2, null=True)
    salt_100g = models.DecimalField(max_digits=4, decimal_places=2, null=True)
    saturate_fat_100g = models.DecimalField(max_digits=4, decimal_places=2, null=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "Produit"

home/forms.py
""" Home App Forms """

from django import forms
import re


class SearchForm(forms.Form):
    """ Form user to search product """

    search = forms.CharField(
        max_length=150,
        widget=forms.TextInput(
            attrs={
                "class": "search_input",
                "name": "text",
                "placeholder": "Rechercher...",
            }
        ),
    )

    def clean_search(self):
        """Search text validation"""

        cleaned_data = super(SearchForm, self).clean()
        text = cleaned_data.get("search")
        text = re.sub(r"\W+", "", text)

        if text == "":
            raise forms.ValidationError("le produit recherché est invalide")

        return text

home/views.py
""" Home Views """

from django.shortcuts import render
from .forms import SearchForm
from . import search as S
from django.core.paginator import Paginator
from django.contrib import messages
from home.management.update_db import update_product

# Create your views here.


def home(request):
    """
    Views for home
    :param request:
    :return render home.html:
    """
    return render(
        request, "home.html", {"form_search": SearchForm(None), "GoToProduct": False}
    )


def mentions(request):
    """
    Views for mentions
    :param request:
    :return render mentions.html:
    """
    return render(request, "mentions.html", {"form_search": SearchForm(None)})


def search(request):
    """
    Views for search
    :param request:
    Search product form user input text
    :return render home.html:
    """
    context = {}
    form = None
    if request.method == "POST":
        form = SearchForm(request.POST)
        if form.is_valid():
            text = form.cleaned_data["search"]
            request.session["text"] = text
    else:
        form = SearchForm(None)
        text = request.session["text"]

    products = S.search_product(text)

    if products.count() > 0:
        GoToProduct = True
        paginator = Paginator(products, 6)
        page = request.GET.get("page")
        products = paginator.get_page(page)
        context["products"] = products
    else:
        messages.warning(
            request, "Il n'y a aucun résultat avec ces termes. Essayez encore !"
        )
        GoToProduct = False

    context["GoToProduct"] = GoToProduct
    context["form_search"] = form

    return render(request, "home.html", context)

home/templates/home.html
{% extends 'layouts/default.html' %}
{% load static %}
{% block body %}
{% load widget_tweaks %}
<script type=text/javascript> $GoToProduct="{{ GoToProduct }}" ;</script> <!-- Masthead-->
    <header class="masthead p-0">
    <div class="row mx-auto align-items-center justify-content-center text-center ">
        <div class="col-lg-10 align-self-end">
            <h1 class="text-uppercase font-weight-bold maintitle">Du gras, oui,
                mais de qualité !</h1>
            <br>
            <h2 class="text-uppercase font-weight-bold maintitle">Trouvez facilement un
                produit de substitution pour ceux que vous consommez
                tout les jours !</h2>
            <br>
            <hr class="divider my-4">
            <br>
            {% if messages %}
            <ul class="messages">
                {% for message in messages %}
                    <li{% if message.tags %} class="{{ message.tags }} font-weight-bold"{% endif %}>{{ message }}</li>
                {% endfor %}
            </ul>
            {% endif %}
        </div>

        <div class="col-lg-6 col-md-6 col-sm-8 align-self-baseline">
            <!--{% if envoi %}Votre message a bien été envoyé !{% endif %}-->
            <form action="{% url 'home:search' %}" method="POST" class="form-horizontal search">
                {{ form_search.search.errors }}
                <div class="searchbar">
                    {% csrf_token %}           
                    {{ form_search.search|add_class:'main-search' }}
                    {{ form_search.search.errors }}
                    <input id="search-button" type="submit" value="Go" class="search_icon search-button"/>   
                </div>       
            </form>
            <br>
            <a class="btn btn-primary btn-xl js-scroll-trigger mt-4" href="#about" title="A propos">Qui sommes nous ?</a>
        </div>
    </div>
</header>
<!-- Product section-->
{% if GoToProduct %}
<input type ="hidden" name= "GoToProduct" value = "1">
{% endif %}

{% if products %}   
<section id = "product"  class = "border border-dark">
    <div class="container-fluid p-0 ">
        <div class="row no-gutters">
            {% for product in products %}   
                <div class="col-lg-4 col-md-6 col-sm-12 product-picture">
                    <a class="portfolio-box product_{{product.name|cut:' '}}" href="{% url 'substitute:search-a-substitute' product_id=product.id %}" title="Subsituts">
                        <img class="mx-auto my-auto rounded img-fluid border-dark" src="{{product.photo}}" alt="Photo du produit"/>
                        <div class="portfolio-box-caption">
                            <div class="project-category text-white-50">{{product.category_id}}</div>
                            <div class="project-name">{{product.name}}</div>
                        </div>
                        <div class="img position-absolute" style=" top: -2rem; right: -2.5rem; max-width: 6rem;">
                            <img class = "nutri" src="{% get_static_prefix %}images/nutriscore/Nutri-score-{{ product.nutriscore }}.svg"
                                style="height: auto; width: 100%;" alt="Nutriscore"></img>
                        </div>
                    </a>
                </div>                    
            {% endfor %}            
        </div>
        <br>
        <div class="row no-gutters product-picture">
            {% if products.paginator.num_pages > 1 %}
                <div class="pagination">
                    {% if products.has_previous %}
                        <a class="pagination-action" href="?page=1" title="Page 1">
                            <i class="fa fa-angle-double-left" aria-hidden="true"></i> </a>
                        <a class="pagination-action" href="?page={{ products.previous_page_number }}" title="Page srécédente">
                            <i class="fa fa-angle-left" aria-hidden="true"></i>
                        </a>
                    {% endif %}
                    {% for num in products.paginator.page_range %}
                        {% if products.number == num %}
                            <span class="pagination-number pagination-current">{{ num }}</span>
                        {% elif num > products.number|add:'-3' and num < products.number|add:'3' %}
                            <a class="pagination-number" href="?page={{ num }}" title="Page N° {{ num }}">{{ num }}</a>
                        {% endif %}
                    {% endfor %}
                    {% if products.has_next %}
                        <a class="pagination-action" href="?page={{ products.next_page_number }}" title="Page suivante">
                            <i class="fa fa-angle-right" aria-hidden="true"></i>
                        </a>
                        <a class="pagination-action" href="?page={{ products.paginator.num_pages }}" title="Dernière page">
                            <i class="fa fa-angle-double-right" aria-hidden="true"></i>
                        </a>1
                    {% endif %}
                </div>
            {% endif %}
        </div>
    </div>    
</section>
{% endif %}

<!-- About section-->
<section class="page-section" id="about">
    <div class="container-fluid">
        <div class="row justify-content-center">
            <div class="col-10 col-sm-10 col-md-8 col-lg-8 text-center about">
                <div class="page-content">
                    <h1 class="">Notre identité</h1>
                    <div class="sections">
                        <hr class="divider my-4" />
                        <section id="de-la-ratatouille-aux-croissants" data-id="1331329">
                            <div class="mod block mod-block-section section-title b-section js-b-section js-cm-blockmanager__section" data-id="1331329" data-ready="true">
                                <h2 data-server="true" class="">De la ratatouille aux croissants</h2>
                            </div>
                            <br><br><br>
                            <div class="mod block mod-block-text b-text js-cm-blockmanager__block" data-block="3098382" 
                                data-help="https://docs.frontify.com/d/2MwJ9kHF57Sc/frontify-style-guide#/product/smart-blocks/rich-text-block" 
                                data-feedback="https://frontify.typeform.com/to/Dj3Utn?block=Rich%20Text%20Block" data-ready="true">
                                <div class="js-b-text__text b-text__text co-editor co-editor--default">
                                    <p>
                                        Pur Beurre est l'initiative de deux amoureux de la gastronomie française, Colette Tatou et Rémy, que vous avez déjà certainement 
                                        rencontrés dans notre excellent restaurant Ratatouille.&nbsp;
                                        <br><br><br>
                                        <b>Colette Tatou</b> : "<i>Nous aimons tous manger, surtout en France ! Personnellement, une baguette fraîche, du bon fromage de chèvre 
                                            et un bon vin rouge me suffisent amplement. Comme tout le monde, je fais mes courses au supermarché. Mais petit à petit je me suis 
                                            rendue compte, surtout lorsque nous avons ouvert le restaurant, que je pouvais remplacer les produits aseptisés que j'avais l'habitude 
                                            d'acheter par de bons produits du terroir Et souvent pour le même prix !</i>"
                                        <br><br><br>
                                        <b>Remy</b> : "<i>Pour ma part je me rendais 
                                            déjà dans bien des magasins car j'aime beaucoup me balader, surtout dans les caves et les cuisines. Je connaissais par coeur le 
                                            contenu des boutiques bio (dont je raffole) ainsi que les ingrédients de tous les aliments vendus. Lorsque Colette m'a demandé si elle 
                                            pouvait remplacer son Nutella matinal par un aliment plus sain, je savais tout de suite où le trouver. L'idée de Pur Beurre était née !</i>"
                                        <br><br>
                                    </p>
                                </div>
                            </div>       
                            <img class = "colette1" src="{% static 'images/portfolio/colette-4.jpg' %}" alt="Photo Colette">               
                        </section>                                       
                    </div>
                    <div class="h-100 align-items-center justify-content-center text-center foto portfolio" id="portfolio">
                        <div class="align-self-end mt-3">
                            <div class="fotorama" data-width="100%" >
                                <img src="{% static 'images/portfolio/ratatouille-11.jpg' %}" alt="Photo Colette">
                                <img src="{% static 'images/portfolio/colette-tatou-full.png' %}" alt="Photo Colette">
                                <img src="{% static 'images/portfolio/colette-2.jpg' %}" alt="Photo Colette">
                                <img src="{% static 'images/portfolio/colette-4.jpg' %}" alt="Photo Colette">
                                <img src="{% static 'images/portfolio/colette-5.jpg' %}" alt="Photo Colette">  
                                <img src="{% static 'images/portfolio/colette-7.jpg' %}" alt="Photo Colette">
                                <img src="{% static 'images/portfolio/colette-9.jpg' %}" alt="Photo Colette">
                                
                                
                                <img src="{% static 'images/portfolio/remy.jpg' %}" alt="Photo Colette">
                                <img src="{% static 'images/portfolio/remi-11.png' %}" alt="Photo Colette">
                                <img src="{% static 'images/portfolio/remy-2.jpg' %}" alt="Photo Colette">
                                <img src="{% static 'images/portfolio/remy-3.jpg' %}" alt="Photo Colette">
                                <img src="{% static 'images/portfolio/remy-4.jpg' %}" alt="Photo Colette">
                                <img src="{% static 'images/portfolio/remy-5.jpg' %}" alt="Photo Colette">
                                <img src="{% static 'images/portfolio/remy-6.jpg' %}" alt="Photo Colette">
                                <img src="{% static 'images/portfolio/remy-7.jpg' %}" alt="Photo Colette">
                                <img src="{% static 'images/portfolio/remy-8.jpg' %}" alt="Photo Colette">
                                <img src="{% static 'images/portfolio/remy-9.jpg' %}" alt="Photo Colette">
                                <img src="{% static 'images/portfolio/remy-10.jpg' %}" alt="Photo Colette">
                            </div>
                        </div>
                    </div>
                </div>
               
            </div>
        </div>
    </div> 
</section>

<!-- Contact section-->
<section class="page-section" id="contact">
    <div class="container-fluid">
        <div class="row justify-content-center">
            <div class="col-10 col-sm-10 col-md-8 col-lg-8 text-center about">
                <div class="page-content">
                    <h2 class="mt-0">Nous somme là pour vous servir !</h2>
                    <hr class="divider my-4" />
                    <p class="mb-5">Besoins d'informations ou de nous faire part de vos idées ? Contactez nous !</p>              
                </div>   
                <div class="row">
                    <div class="col-lg-4 ml-auto text-center mb-5 mb-lg-0">
                        <i class="fas fa-phone fa-3x mb-3 text-muted"></i>
                        <div>+33 0405060708</div>
                    </div>
                    <div class="col-lg-4 mr-auto text-center">
                        <i class="fas fa-envelope fa-3x mb-3 text-muted"></i>
                        <a class="d-block" href="mailto:aai@bienmanger.fr" title="email">aai@bienmanger.fr</a>
                    </div>
                </div>
            </div>
        </div>
    </div> 
</section>
{% endblock %}

home/templates/mentions.html
{% extends "layouts/default.html" %}
{% load static %}
{% block body %}
<section class="page-section bg-secondary result h-100">
    <div class="container-fluid col-8 col-sm-8">
        <div class="card mentions">
            <div class="row text-center justify-content-center">
                <div class="col-auto">
                    <h1 class="rounded p-1"><strong>Mention légale</strong></h1>
                </div>
            </div>
            <br>
            <br>
            <div class="row">
                <div class="col-lg-6">
                    <p>Nom:</p>
                </div>
                <div class="col-lg-6">
                    <p>ANSELMI</p>
                </div>
            </div>
            <div class="row">
                <div class="col-lg-6">
                    <p>Prénom:</p>
                </div>
                <div class="col-lg-6">
                    <p>Arnaud</p>
                </div>
            </div>
            <div class="row">
                <div class="col-lg-6">
                    <p>Adresse:</p>
                </div>
                <div class="col-lg-6">
                    <p>1 rue des lillas, Nice</p>
                </div>
            </div>
            <div class="row">
                <div class="col-lg-6">
                    <p>Téléphone:</p>
                </div>
                <div class="col-lg-6">
                    <p>06 00 00 00 00</p>
                </div>
            </div>
            <div class="row">
                <div class="col-lg-6">
                    <p>Coordonnées de l'hebergeur:</p>
                </div>
                <div class="col-lg-6">
                    <p>Heroku </br>
                        50 Fremont St.</br>
                        Suite 300</br>
                        San Francisco, CA</br>
                        94105</p>
                </div>
            </div>
            <div class="row">
                <div class="col-lg-6">
                    <p>Template utilisé: </p>
                </div>
                <div class="col-lg-6">
                    <a href="https://blackrockdigital.github.io/startbootstrap-creative/" title="template"
                        class="btn btn-primary">startbootstrap-creative</a>
                </div>
            </div>
            <div class="row">
                <div class="col-lg-6">
                    <p>Chartes graphique utilisé:</p>
                </div>
                <div class="col-lg-6">
                    <a href="https://company-82435.frontify.com/d/6Yy9WFJdtp8j/pur-beurre-style-guide"
                        title="Charte Graphique" class="btn btn-primary mb-2">Photos, icone, couleur</a></br>
                    <a href="https://fontawesome.com/icons" class="btn btn-primary" title="Icônes">Icones des menus</a>
                </div>
            </div>
        </div>
    </div>
</section>
{% endblock body %}