account/urls.py
"""Contains the application’s url."""
from django.urls import path
from . import views

app_name = "account"

urlpatterns = [
    path("login/", views.login, name="login"),
    path("logout/", views.logout, name="logout"),
    path("profile/", views.profile, name="profile"),
    path("favorites/", views.favorites, name="favorites"),
    path("register/", views.register, name="register"),
]

home/urls.py
"""Contains the application’s url."""
from django.urls import path
from . import views

app_name = "home"

urlpatterns = [
    path("", views.home, name="index"),
    path("mentions/", views.mentions, name="mentions"),
    path("product/", views.search, name="search"),
    path("product/?page=<int:page>", views.search, name="search"),
]

purbeurre/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("", include("home.urls")),
    path("", include("substitute.urls")),
    path("", include("account.urls")),
    path("admin/", admin.site.urls),
]

substitute/urls.py
"""Contains the application’s url."""
from django.urls import path
from . import views

app_name = "substitute"

urlpatterns = [
    path("substitute/<int:product_id>", views.substitute, name="search-a-substitute"),
    path(
        "substitute/<int:product_id>/?page=<int:page>",
        views.substitute,
        name="search-a-substitute",
    ),
    path("detail/<int:product_id>/<int:substitute_id>/", views.detail, name="detail"),
    path("save/<int:product_id>/<int:substitute_id>/", views.save, name="save"),
    path(
        "detail_favoris/<int:product_id>/<int:substitute_id>/",
        views.detail_favoris,
        name="detail_favoris",
    ),
]

substitute/models.py
from django.db import models
from home.models import Product
from django.conf import settings


class Substitute(models.Model):
    """ Favorites """

    product_id = models.ForeignKey(
        Product, related_name="product", on_delete=models.CASCADE
    )
    substitute_id = models.ForeignKey(
        Product, related_name="substitute", on_delete=models.CASCADE
    )

    user_id = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)

    class Meta:
        constraints = [
            models.UniqueConstraint(
                fields=["product_id", "substitute_id", "user_id"],
                name="unique_relation",
            )
        ]
        verbose_name = "Favoris"
        verbose_name_plural = "Favoris"

substitute/views.py
from django.shortcuts import render, redirect
from home import search
from .models import Substitute
from home.models import Product
from home.forms import SearchForm
from django.core.paginator import Paginator
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.urls import reverse


def substitute(request, product_id):
    if request.method == "GET":
        substitutes = search.search_substitute(product_id)
        if substitutes.count() > 0:
            paginator = Paginator(substitutes, 6)
            page = request.GET.get("page")
            substitutes = paginator.get_page(page)
            context = {}
            context["substitutes"] = substitutes
            context["title"] = "Substituts"
            context["product"] = Product.objects.get(pk=product_id)
            context["form_search"] = SearchForm(None)

            return render(request, "substitute.html", context)
        else:
            messages.warning(request, "Il n'y a pas de substitut pour ce produit")
            return redirect("home:index")


def detail(request, product_id, substitute_id):
    if request.method == "GET":
        try:
            substitute = Product.objects.get(pk=substitute_id)
            product = Product.objects.get(pk=product_id)
            if substitute is not None:
                context = {}
                context["product"] = product
                context["substitute"] = substitute
                context["title"] = "Détails du produit " + substitute.name
                if request.user.is_authenticated:
                    context["exist"] = Substitute.objects.filter(
                        user_id=request.user,
                        product_id=product,
                        substitute_id=substitute,
                    ).exists()
                context["form_search"] = SearchForm(None)

                return render(request, "detail.html", context)
            else:
                messages.warning(
                    request,
                    "Il y a eu une lors de la récupération des information du substitut",
                )
                return render(request, "home.html", {"form_search": SearchForm(None)})
        except:  # pragma: no cover
            messages.warning(
                request,
                "Il y a eu une lors de la récupération des information du substitut",
            )
            return render(request, "home.html", {"form_search": SearchForm(None)})


@login_required
def save(request, product_id, substitute_id):
    if request.method == "GET" and product_id and substitute_id:
        substitute = Product.objects.get(pk=substitute_id)
        product = Product.objects.get(pk=product_id)
        context = {}
        context["product"] = product
        context["substitute"] = substitute
        context["title"] = "Détails du produit " + substitute.name
        try:
            user_product = Substitute(
                user_id=request.user, product_id=product, substitute_id=substitute
            )
            user_product.save()
            messages.success(request, "Votre substitut a été sauvé")
            context["exist"] = True

        except:  # pragma: no cover
            messages.warning(request, "Erreur lors de l'enregistrement du favoris")

        context["form_search"] = SearchForm(None)
        return render(request, "detail.html", context)


@login_required
def detail_favoris(request, product_id, substitute_id):
    if request.method == "GET":
        context = {}
        context["form_search"] = SearchForm(None)
        substitute = Product.objects.get(pk=substitute_id)
        product = Product.objects.get(pk=product_id)
        if substitute is not None and product is not None:
            context["product"] = product
            context["substitute"] = substitute
            context["title"] = "Détails du favoris"
            return render(request, "detail_favoris.html", context)
        else:  # pragma: no cover
            messages.warning(
                request,
                "Il y a eu une erreur lors de la récupération des informations du favoris",
            )
            return redirect(reverse('home:index'))

substitute/templates/detail.html
{% extends 'layouts/default.html' %}
{% load static %}

{% block body %}
<div class="product_result">
    <header>
        <div class="container-fluid p-0">
            <br>
            <br>
            <br>
            <br>
            <div class="row h-100 mb-3 align-items-center justify-content-center text-center">
                {% if messages %}
                <ul class="messages">
                    {% for message in messages %}
                    <h4{% if message.tags %} class="{{ message.tags }} font-weight-bold" style="color:white"
                        {% endif %}>{{ message }}</h4>
                        {% endfor %}
                </ul>
                {% endif %}
            </div>
        </div>
    </header>
    <div class="container-fluid col-8 col-sm-8">
        <div class="p-1">
            <div class="card detail">
                <div class="row">
                    <h4 class="mx-auto title align-items-center justify-content-center text-center">
                        {{ substitute.name }}
                    </h4>
                </div>
                <div class="wrapper row">
                    <div
                        class="preview col-sm-8 col-md-4 mt-5 mx-auto align-items-center justify-content-center text-center">
                        <div class="tab-content">
                            <div class="tab-pane active mx-auto align-items-center justify-content-center text-center">
                                <div class="preview-pic">
                                    <img class="img w-100" src="{{ substitute.photo }}" alt="Photo du produit">
                                </div>
                                <br>
                                <div>
                                    <img data-target="#pic-1" data-toggle="tab" class="detail_nutri"
                                        src="{% get_static_prefix %}images/nutriscore/Nutri-score-{{ substitute.nutriscore }}.svg"
                                        alt="Nutriscore">
                                    </img>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="details col-sm-12 col-md-8">

                        <div class="table-responsive-md my-5 w-75 mx-auto" style="font-family: Open Sans, sans-serif;">
                            <table class="table table-md table-striped table-bordered">
                                <thead>
                                    <tr class="bg-primary">
                                        <th class="lead">Valeurs nutritionelles :</th>
                                        <th scope="col">pour 100g</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    <tr>
                                        <th scope="row">matières grasses : </th>
                                        <td>{{ substitute.fat_100g }} g</td>
                                    </tr>
                                    <tr>
                                        <th scope="row">dont saturées : </th>
                                        <td>{{ substitute.saturate_fat_100g }} g</td>
                                    </tr>
                                    <tr>
                                        <th scope="row">sels : </th>
                                        <td>{{ substitute.salt_100g }} g</td>
                                    </tr>
                                    <tr>
                                        <th scope="row">dont sucres : </th>
                                        <td>{{ substitute.sugars_100g }} g</td>
                                    </tr>
                                </tbody>
                            </table>
                        </div>
                        <div class="preview-pic tab-content mx-auto">
                            <div class="tab-pane active" id="pic-1">
                                <img class="img w-100" src="{{ substitute.ingredients }}" alt="Ingrédients du produit">
                            </div>
                        </div>
                    </div>
                </div>
                <br>
                <div class="action mx-auto">
                    <a href="{{ substitute.url }}" title="Fiche Produit d'OpenFoodFact" target="_blank"
                        class="mx-auto visit-site">
                        <button type="button" class="btn-lg btn-danger text-light font-weight-light mx-auto">Voir La
                            Fiche d'OpenFoodFacts</button>
                    </a>
                </div>
                <br>
                <div class="row px-3 mx-auto">
                    {% if user.is_authenticated %}
                    {% if not exist %}
                    <div>
                        <p>Sauver ce substitut ? <a
                                href="{% url 'substitute:save' product_id=product.id substitute_id=substitute.id %}"
                                title="Sauveguarder Favoris" class="font-weight-bold"><i class="fa fa-save"
                                    style="font-size:16px;color:green;"> Enregistrer</i></a></p>
                    </div>
                    {% else %}
                    <div>
                        <p>Vous avez déjà enregistré ce substitut</p>
                    </div>
                    {% endif %}
                    {% else %}
                    <div>
                        <p>Vous devez vous connecter pour enregistrer ce substitut <a
                                href="{% url 'account:login' %}?next={{request.path}}" title="Se connecter"
                                class="font-weight-bold"><i class="fa fa-user" style="color:orange;"> Se
                                    connecter</i></a></p>
                    </div>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

substitute/templates/detail_favoris.html
{% extends 'layouts/default.html' %}
{% load static %}

{% block body %}
<header class="masthead">
    <div class="container-fluid p-2 product_result">
        <br>
        <br>
        <br>
        <div class="row h-100 mb-3 align-items-center justify-content-center text-center">
            {% if messages %}
            <ul class="messages">
                {% for message in messages %}
                <h4{% if message.tags %} class="{{ message.tags }} font-weight-bold" {% endif %}>{{ message }}</h4>
                    {% endfor %}
            </ul>
            {% endif %}
            <div class="row mx-auto">
                <div class="col-lg-6 col-md-10 col-sm-10 wrapper justify-content-center text-center px-3 mx-auto">
                    <div class="card text-white detail">
                        <div class="row no-gutters title-3 -dark">
                            <h4 class="mx-auto">Détail du produit</h4>
                        </div>
                        <div class="row no-gutters title-2">
                            <h4 class="mx-auto">{{ product.name }}</h4>
                        </div>
                        <div class="card-body">
                            <div>
                                <div class="row">
                                    <div class="col-md-6 col-sm-12 pro">
                                        <div class="preview-pic tab-content">
                                            <div class="tab-pane active mx-auto align-items-center justify-content-center text-center"
                                                id="pic-1"><img class="img" src="{{ product.photo }}"
                                                    alt="Photo du produit">
                                            </div>
                                        </div>
                                        <br>
                                        <img class="score"
                                            src="{% get_static_prefix %}images/nutriscore/Nutri-score-{{ product.nutriscore }}.svg"
                                            alt="Nutriscore"></img>
                                    </div>
                                    <div class="col-md-6 col-sm-12">
                                        <div class="table-responsive-md w-100 mx-auto"
                                            style="font-family: Open Sans, sans-serif;">
                                            <table class="table table-md table-striped table-bordered">
                                                <thead>
                                                    <tr class="bg-primary">
                                                        <th class="lead">Valeurs nutritionelles</th>
                                                        <th scope="col">pour 100g</th>
                                                    </tr>
                                                </thead>
                                                <tbody>
                                                    <tr>
                                                        <th scope="row">matières grasses</th>
                                                        <td>{{ product.fat_100g }} g</td>
                                                    </tr>
                                                    <tr>
                                                        <th scope="row">dont saturées</th>
                                                        <td>{{ product.saturate_fat_100g }} g</td>
                                                    </tr>
                                                    <tr>
                                                        <th scope="row">sels</th>
                                                        <td>{{ product.salt_100g }} g</td>
                                                    </tr>
                                                    <tr>
                                                        <th scope="row">sucres</th>
                                                        <td>{{ product.sugars_100g }} g</td>
                                                    </tr>
                                                </tbody>
                                            </table>
                                        </div>

                                        <div class="preview-pic tab-content mx-auto">
                                            <div class="tab-pane active" id="pic-1"><img class="img w-100"
                                                    src="{{ product.ingredients }}" alt="Ingrédients du produit">
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="card-footer">
                            <div class="action mx-auto align-items-center justify-content-center text-center">
                                <a href="{{ product.url }}" title="Fiche produit OpenFoodFact" target="_blank"
                                    class="mx-auto">
                                    <button type="button"
                                        class="btn-lg btn-danger my-1 text-light font-weight-light mx-auto">Voir la
                                        fiche d'OpenFoodFacts</button>
                                </a>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-lg-6 col-md-10 col-sm-10 wrapper justify-content-center text-center px-3 mx-auto">
                    <div class="card text-white detail">
                        <div class="row no-gutters title-3 -dark">
                            <h4 class="mx-auto">Détail du substitut</h4>
                        </div>
                        <div class="row no-gutters title-2">
                            <h4 class="mx-auto">{{ substitute.name }}</h4>
                        </div>
                        <div class="card-body">
                            <div>
                                <div class="row">
                                    <div class="col-md-6 col-sm-12">
                                        <div class="preview-pic tab-content">
                                            <div class="tab-pane active mx-auto align-items-center justify-content-center text-center"
                                                id="pic-1"><img class="img" src="{{ substitute.photo }}"
                                                    alt="Photo du produit"></div>
                                        </div>
                                        <br>
                                        <img class="score"
                                            src="{% get_static_prefix %}images/nutriscore/Nutri-score-{{ substitute.nutriscore }}.svg"
                                            alt="nutriscore"></img>
                                    </div>
                                    <div class="col-md-6 col-sm-12">
                                        <div class="table-responsive-md w-100 mx-auto"
                                            style="font-family: Open Sans, sans-serif;width:100%;">
                                            <table class="table table-md table-striped table-bordered">
                                                <thead>
                                                    <tr class="bg-primary">
                                                        <th class="lead">Valeurs nutritionelles</th>
                                                        <th scope="col">pour 100g</th>
                                                    </tr>
                                                </thead>
                                                <tbody>
                                                    <tr>
                                                        <th scope="row">matières grasses</th>
                                                        <td>{{ substitute.fat_100g }} g</td>
                                                    </tr>
                                                    <tr>
                                                        <th scope="row">dont saturées</th>
                                                        <td>{{ substitute.saturate_fat_100g }} g</td>
                                                    </tr>
                                                    <tr>
                                                        <th scope="row">sels</th>
                                                        <td>{{ substitute.salt_100g }} g</td>
                                                    </tr>
                                                    <tr>
                                                        <th scope="row">sucres</th>
                                                        <td>{{ substitute.sugars_100g }} g</td>
                                                    </tr>
                                                </tbody>
                                            </table>
                                        </div>

                                        <div class="preview-pic tab-content mx-auto">
                                            <div class="tab-pane active" id="pic-1"><img class="img w-100"
                                                    src="{{ substitute.ingredients }}" alt="Ingrédients du produit">
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="card-footer">
                            <div class="action mx-auto align-items-center justify-content-center text-center">
                                <a href="{{ substitute.url }}" title="Fiche produit OpenFoodFact" target="_blank"
                                    class="mx-auto">
                                    <button type="button"
                                        class="btn-lg btn-danger my-1 text-light font-weight-light mx-auto">Voir la
                                        fiche d'OpenFoodFacts</button>
                                </a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <br>
        <br>
    </div>
</header>
{% endblock %}

substitute/templates/favorites.html
{% extends 'layouts/default.html' %}
{% load static %}
{% block body %}
<header class="masthead" id="favorites">
    <div class="col-md-8 col-xl-6 container card favorites shadow-lg">
        <div class="card-header msg_head d-flex mx-auto font-weight-bold">
            <div class="mx-auto bd-highlight">
                <br>
                {% if messages %}
                <ul class="messages">
                    {% for message in messages %}
                    <h4{% if message.tags %} class="{{ message.tags }} font-weight-bold" {% endif %}>{{ message }}</h4>
                        {% endfor %}
                </ul>
                {% endif %}
                <h3>Mes Favoris</h3>
            </div>
        </div>
        <div class="card-body" id="msg_card_body">
            <div class="d-flex justify-content-start">
                <div
                    class="table-responsive-md my-auto w-75 mx-auto align-items-center justify-content-center text-center">
                    <table
                        class="table table-md table-striped table-bordered align-items-center justify-content-center text-center">
                        <thead>
                            <tr>
                                <th class="lead">Produit</th>
                                <th scope="col">Substitut</th>
                                <th scope="col">Détails</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for favori in favoris %}
                            <tr>
                                <th scope="row"><img class="img align-items-center justify-content-center text-center"
                                        src="{{ favori.product_id.photo }}" alt="Photo du produit"></th>
                                <td class="align-items-center justify-content-center text-center"><img class="img"
                                        src="{{ favori.substitute_id.photo }}" alt="Photo du Produit">
                                </td>
                                <td class="align-items-center justify-content-center text-center"><a
                                        href="{% url 'substitute:detail_favoris' product_id=favori.product_id.id substitute_id=favori.substitute_id.id %}"
                                        title="Détails du favori" name="favori {{forloop.counter}}">Voir</a></td>
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
    <br>
    <br>
    <br>
</header>
{% endblock %}

substitute/templates/substitute.html
{% extends 'layouts/default.html' %}
{% load static %}
{% block body %}
<header class="masthead border border-dark">
    <div class="col-lg-4 col-sm-6 mb-3">
        <div class="justify-content-center text-center">
            <div class="product_img font-weight-bold">
                <div class="text-uppercase project-category">{{product.category_id}}</div>
                <br>
                <div class="text-uppercase project-name">{{product.name}}</div>
            </div>
            <br>
            <hr class="divider my-4">
            <br>
            <div>
                <img class="product_img" src="{{product.photo}}" alt="Photo du produit"><img />
            </div>
            <br>
            <div class="img product_sample mx-auto">
                <img class="nutri"
                    src="{% get_static_prefix %}images/nutriscore/Nutri-score-{{ product.nutriscore }}.svg"
                    alt="Nutriscore">
                </img>
            </div>
        </div>
    </div>
</header>

<section id="product">
    <div class="container-fluid p-4 substitute">
        <div class="row align-items-center justify-content-center text-center">
            <h2>Vous pouvez remplacez cet aliment par :</h2>
        </div>
        <br>
        <div class="row no-gutters">
            {% for substitute in substitutes %}
            <div class="col-lg-4 col-sm-6 product-picture">
                <a class="portfolio-box substitute_{{substitute.name|cut:' '}}"
                    href="{% url 'substitute:detail' product_id=product.id substitute_id=substitute.id %}"
                    title="Détails du produit">
                    <img class="img-responsive rounded product-image-size-max" src="{{substitute.photo}}"
                        alt="Photo du produit" />
                    <div class="portfolio-box-caption">
                        <div class="project-category text-white-50">{{substitute.category_id}}</div>
                        <div class="project-name">{{substitute.name}}</div>
                    </div>
                    <div class="img position-absolute" style=" top: -2rem; right: -2.5rem; max-width: 6rem;">
                        <img class="nutri"
                            src="{% get_static_prefix %}images/nutriscore/Nutri-score-{{ substitute.nutriscore }}.svg"
                            style="height: auto; width: 100%;" alt="Nutriscore"></img>
                    </div>
                </a>
            </div>
            {% endfor %}
        </div>
        <div class="row no-gutters product-picture mb-5">
            {% if substitutes.paginator.num_pages > 1 %}
            <div class="pagination">
                {% if substitutes.has_previous %}
                <a class="pagination-action" href="?page=1" title="Page 1">
                    <i class="fa fa-angle-double-left" aria-hidden="true"></i> </a>
                <a class="pagination-action" href="?page={{ substitutes.previous_page_number }}"
                    title="Page srécédente">
                    <i class="fa fa-angle-left" aria-hidden="true"></i>
                </a>
                {% endif %}
                {% for num in substitutes.paginator.page_range %}
                {% if substitutes.number == num %}
                <span class="pagination-number pagination-current">{{ num }}</span>
                {% elif num > substitutes.number|add:'-3' and num < substitutes.number|add:'3' %}
                <a class="pagination-number" href="?page={{ num }}" title="Page N° {{ num }}">{{ num }}</a>
                {% endif %}
                {% endfor %}
                {% if substitutes.has_next %}
                <a class="pagination-action" href="?page={{ substitutes.next_page_number }}" title="Page suivante">
                    <i class="fa fa-angle-right" aria-hidden="true"></i>
                </a>
                <a class="pagination-action" href="?page={{ substitutes.paginator.num_pages }}">
                    <i class="fa fa-angle-double-right" aria-hidden="true" title="Dernière page"></i>
                </a>1
                {% endif %}
            </div>
            {% endif %}
        </div>
    </div>
</section>

{% endblock %}