account/urls.py
"""Contains the application’s url."""
from django.urls import path
from . import views

app_name = "account"

urlpatterns = [
    path("login/", views.login, name="login"),
    path("logout/", views.logout, name="logout"),
    path("profile/", views.profile, name="profile"),
    path("favorites/", views.favorites, name="favorites"),
    path("register/", views.register, name="register"),
]

home/urls.py
"""Contains the application’s url."""
from django.urls import path
from . import views

app_name = "home"

urlpatterns = [
    path("", views.home, name="index"),
    path("mentions/", views.mentions, name="mentions"),
    path("product/", views.search, name="search"),
    path("product/?page=<int:page>", views.search, name="search"),
]

purbeurre/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("", include("home.urls")),
    path("", include("substitute.urls")),
    path("", include("account.urls")),
    path("admin/", admin.site.urls),
]

account/models.py
"""Account App models"""

from django.contrib.auth.models import AbstractUser
from django.contrib.auth.models import User


# Create your models here.
class User(AbstractUser):
    """ User class inherit from AbstractUser """

    pass

account/forms.py
from django import forms
from account.models import User
from django.contrib.auth.forms import (
    UserChangeForm,
    UserCreationForm,
    AuthenticationForm,
)


class ConnexionForm(AuthenticationForm):
    class Meta:
        model = User
        fields = ("username", "password")


class SignUpForm(UserCreationForm):
    email = forms.EmailField(
        max_length=254, help_text="Rentrer une adresse email valide"
    )
    robot = forms.BooleanField(required=True)

    class Meta:
        model = User
        fields = (
            "username",
            "email",
            "password1",
            "password2",
        )


class UserUpdateForm(UserChangeForm):
    class Meta:
        model = User
        fields = ("username", "email")

account/views.py
""" Imports """

from django.contrib.auth import authenticate, login as auth_login, logout as auth_logout
from .forms import ConnexionForm, UserUpdateForm, SignUpForm
from home.forms import SearchForm
from django.shortcuts import render, redirect, HttpResponseRedirect
from django.urls import reverse
from django.contrib import messages
from substitute.models import Substitute
from django.contrib.auth.decorators import login_required


@login_required
def favorites(request):
    """
    @require login
    Views for favorites
    :param request:
    :return render favorites.html:
    """
    favoris = Substitute.objects.filter(user_id=request.user)
    return render(
        request, "favorites.html", {"favoris": favoris, "form_search": SearchForm(None)}
    )


@login_required
def profile(request):
    """
    @require login
    Views for profile
    :param request:
    :return render profile.html:
    """

    if request.method == "POST":
        form = UserUpdateForm(request.POST, instance=request.user)
        try:
            if form.is_valid():
                form.save()
                messages.success(
                    request,
                    "Les modifications de votre profil ont bien été enregistrées",
                )
        except:  # pragma: no cover
            messages.error(
                request,
                "Erreurs durant l'enregistrement des informations de votre profil",
            )
    else:
        form = UserUpdateForm(instance=request.user)

    return render(
        request, "profile.html", {"form": form, "form_search": SearchForm(None)}
    )


def login(request):
    """
    Views for login
    :param request:
    :return
    if method post and login ok
        if previous page exist : render last visited page
        else: render home.html
    else
        render login.html
    :
    """
    if request.user.is_authenticated:
        return redirect(reverse("home:index"))
    else:
        if request.method == "POST":
            form = ConnexionForm(data=request.POST)
            try:
                if form.is_valid():
                    user = authenticate(
                        username=form.cleaned_data["username"],
                        password=form.cleaned_data["password"],
                    )
                    try:
                        if user:
                            auth_login(request, user)
                            request.session.set_expiry(900)
                            return HttpResponseRedirect(request.session["previous"])
                        else:
                            messages.error(request, "Mauvais login/mot de passe.")
                            return render(request, "login.html", {"form": form})
                    except:  # pragma: no cover
                        redirect(reverse("home:index"))
            except Exception as e:  # pragma: no cover
                messages.error(request, "Erreur de login.")
                return render(request, "login.html", {"form": form})
        else:
            form = ConnexionForm(None)
            request.session["previous"] = request.META.get("HTTP_REFERER")

        return render(
            request, "login.html", {"form": form, "form_search": SearchForm(None)}
        )


def register(request):
    """
    Views for register
    :param request:
    :return
    if method post and form valid
        create user, login and redirect to home.html
    else
        render register.html
    :
    """
    if request.method == "POST":
        form = SignUpForm(request.POST)
        try:
            if form.is_valid():
                form.save()
                username = form.cleaned_data.get("username")
                raw_password = form.cleaned_data.get("password1")
                user = authenticate(username=username, password=raw_password)
                auth_login(request, user)
                return redirect(reverse("home:index"))

        except Exception as e:
            messages.error(request, "Votre compte n'a pas été crée.")
    else:
        form = SignUpForm(None)

    return render(
        request, "register.html", {"form": form, "form_search": SearchForm(None)}
    )


@login_required
def logout(request):
    """
    @require login
    Views for logout
    :param request:
    :return reditrect to home.html:
    """
    auth_logout(request)
    return redirect(reverse("home:index"))

account/templates/login.html
{% extends 'layouts/default.html' %}
{% load static %}

{% block body %}

<body>
    <div class="container-fluid align-items-center justify-content-center login">
        <div class="justify-content-center innerlogin">
            <div class="col-sm-10 col-md-6 col-lg-4 mx-auto mt-5 text-center">
                <div class="card card-signin my-5">
                    <div class="card-body mt-5">
                        <h5 class="card-title text-center">Connexion</h5>
                        <br>
                        {% if messages %}
                        <ul class="messages">
                            {% for message in messages %}
                            <li{% if message.tags %} class="{{ message.tags }}" {% endif %}>{{ message }}</li>
                                {% endfor %}
                        </ul>
                        {% endif %}
                        <br>
                        <form class="form-signin" method="POST" action="{% url 'account:login' %}">
                            {% csrf_token %}
                            {{ form.non_field_errors }}
                            {% if not user.is_authenticated %}
                            <div class="form-label-group">
                                {{ form.username }}
                                <label for="inputEmail">{{ form.username.label_tag }}</label>
                                {{ form.username.errors }}
                            </div>
                            <div class="form-label-group">
                                {{ form.password }}
                                <label for="inputPassword">{{ form.password.label_tag }}</label>
                                {{ form.password.errors }}
                            </div>
                            <button name="submit" class="btn btn-lg btn-primary btn-block text-uppercase"
                                type="submit">Connexion</button>

                            <br>
                            <div>
                                <p>Pas encore enregistré ? <a href="{% url 'account:register' %}" title="s'enregistrer"
                                        id="register"><i class="fa fa-user-plus"
                                            style="font-size:32px;color:orange"></i></a></p>
                            </div>
                            {% endif %}
                        </form>

                    </div>
                </div>
            </div>
        </div>
    </div>
</body>

{% endblock body %}

account/templates/profile.html
{% extends 'layouts/default.html' %}
{% load static %}

{% block body %}
<link href="{% static 'css/login.css' %}" rel="stylesheet">

<body>
    <div class="container-fluid align-items-center justify-content-center login">
        <div class="justify-content-center innerlogin">
            <div class="col-sm-9 col-md-7 col-lg-5 mx-auto mt-5">
                <div class="card card-signin my-5">
                    <div class="card-body mt-5">
                        <h5 class="card-title text-center">Profile Utilisateur</h5>
                        <br>
                        {% if messages %}
                        <ul class="messages">
                            {% for message in messages %}
                            <li{% if message.tags %} class="{{ message.tags }}" {% endif %}>{{ message }}</li>
                                {% endfor %}
                        </ul>
                        {% endif %}
                        <br>
                        <form class="form-signin" method="POST" action="{% url 'account:profile' %}">
                            {% csrf_token %}
                            {{ form.non_field_errors }}
                            {% if user.is_authenticated %}
                            <div class="form-label-group">
                                {{ form.username }}
                                <label for="inputUsername">{{ form.username.label_tag }}</label>
                                {{ form.username.errors }}
                            </div>
                            <div class="form-label-group">
                                {{ form.email }}
                                <label for="inputEmail">{{ form.email.label_tag }}</label>
                                {{ form.email.errors }}
                            </div>
                            <br>
                            <p class="nav-item font-weight-bold"><a class="nav-link js-scroll-trigger"
                                    href="{% url 'account:favorites' %}" title="favoris"
                                    style="color:#C45525 !important;"><i class="fa fa-star fa-lg"
                                        aria-hidden="true"></i> Mes Favoris</a></p>
                            <br>
                            <button name="confirm_change"
                                class="disabled btn btn-lg btn-primary btn-block text-uppercase" type="submit"
                                disabled>Valider</button>
                            {% endif %}
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</body>

{% endblock body %}

account/templates/register.html
{% extends 'layouts/default.html' %}
{% load static %}

{% block body %}

<body>
    <div class="container-fluid align-items-center justify-content-center login" id="register-user">
        <div class="justify-content-center innerlogin">
            <div class="col-sm-9 col-md-7 col-lg-5 mx-auto mt-5">
                <div class="card card-signin my-5">
                    <div class="card-body">
                        <h5 class="card-title text-center">S'enregistrer</h5>
                        <br>
                        <form class="form-signin" method="POST" action="{% url 'account:register' %}">
                            {% csrf_token %}
                            {{ form.non_field_errors }}
                            {% if user.is_authenticated %}
                            Vous êtes connecté, {{ user.username }} !
                            {% else %}
                            <div class="form-label-group">
                                {{ form.username}}
                                <label>{{ form.username.label_tag}}</label>
                                {{ form.username.errors}}
                            </div>
                            <div class="form-label-group">
                                {{ form.email }}
                                <label>{{ form.email.label_tag }}</label>
                                {{ form.email.errors }}
                            </div>
                            <div class="form-label-group">
                                {{ form.password1 }}
                                <label>{{ form.password1.label_tag }}</label>
                                {{ form.password1.errors }}
                            </div>
                            <div class="form-label-group">
                                {{ form.password2 }}
                                <label>{{ form.password2.label_tag }}</label>
                                {{ form.password2.errors }}
                            </div>
                            <label>{{ form.robot }} Je ne suis pas un robot</label>
                            {{ form.robot.errors }}
                            <br>
                            <button id='submit' class="btn btn-lg btn-primary btn-block text-uppercase"
                                type="submit">S'enregitrer</button>
                            <br>
                            <div>
                                <p>Déjà un compte ? <a href="{% url 'account:login' %}" title="se connecter"><i
                                            class="fa fa-user" style="font-size:32px;color:orange"></i></a></p>
                            </div>
                            {% endif %}
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</body>

{% endblock body %}