account/urls.py
"""Contains the application’s url."""
from django.urls import path
from . import views

app_name = "account"

urlpatterns = [
    path("login/", views.login, name="login"),
    path("logout/", views.logout, name="logout"),
    path("profile/", views.profile, name="profile"),
    path("favorites/", views.favorites, name="favorites"),
    path("register/", views.register, name="register"),
]

home/urls.py
"""Contains the application’s url."""
from django.urls import path
from . import views

app_name = "home"

urlpatterns = [
    path("", views.home, name="index"),
    path("mentions/", views.mentions, name="mentions"),
    path("product/", views.search, name="search"),
    path("product/?page=<int:page>", views.search, name="search"),
]

purbeurre/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("", include("home.urls")),
    path("", include("substitute.urls")),
    path("", include("account.urls")),
    path("admin/", admin.site.urls),
]

home/models.py
from django.db import models


class Category(models.Model):
    """ Product Categories """

    name = models.CharField(max_length=100, unique=True, verbose_name="Nom")

    class Meta:
        verbose_name = "Catégorie"

    def __str__(self):
        return self.name


class Product(models.Model):
    """ Product """

    name = models.CharField(max_length=100, unique=True, verbose_name="Nom du produit")
    category_id = models.ForeignKey(
        Category,
        related_name="category",
        verbose_name="Catégorie ID",
        on_delete=models.CASCADE,
    )

    nutriscore = models.CharField(max_length=1, verbose_name="Nutriscore")
    url = models.URLField(unique=True, verbose_name="URL")
    photo = models.URLField(verbose_name="Photo")
    ingredients = models.URLField(verbose_name="Ingredients", null=True)
    fat_100g = models.DecimalField(max_digits=4, decimal_places=2, null=True)
    sugars_100g = models.DecimalField(max_digits=4, decimal_places=2, null=True)
    salt_100g = models.DecimalField(max_digits=4, decimal_places=2, null=True)
    saturate_fat_100g = models.DecimalField(max_digits=4, decimal_places=2, null=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "Produit"

home/forms.py
""" Home App Forms """

from django import forms
import re


class SearchForm(forms.Form):
    """ Form user to search product """

    search = forms.CharField(
        max_length=150,
        widget=forms.TextInput(
            attrs={
                "class": "search_input",
                "name": "text",
                "placeholder": "Rechercher...",
            }
        ),
    )

    def clean_search(self):
        """Search text validation"""

        cleaned_data = super(SearchForm, self).clean()
        text = cleaned_data.get("search")
        text = re.sub(r"\W+", "", text)

        if text == "":
            raise forms.ValidationError("le produit recherché est invalide")

        return text

home/views.py
""" Home Views """

from django.shortcuts import render
from .forms import SearchForm
from . import search as S
from django.core.paginator import Paginator
from django.contrib import messages
from home.management.update_db import update_product

# Create your views here.


def home(request):
    """
    Views for home
    :param request:
    :return render home.html:
    """
    return render(
        request, "home.html", {"form_search": SearchForm(None), "GoToProduct": False}
    )


def mentions(request):
    """
    Views for mentions
    :param request:
    :return render mentions.html:
    """
    return render(request, "mentions.html", {"form_search": SearchForm(None)})


def search(request):
    """
    Views for search
    :param request:
    Search product form user input text
    :return render home.html:
    """
    context = {}
    form = None
    if request.method == "POST":
        form = SearchForm(request.POST)
        if form.is_valid():
            text = form.cleaned_data["search"]
            request.session["text"] = text
    else:
        form = SearchForm(None)
        text = request.session["text"]

    products = S.search_product(text)

    if products.count() > 0:
        GoToProduct = True
        paginator = Paginator(products, 6)
        page = request.GET.get("page")
        products = paginator.get_page(page)
        context["products"] = products
    else:
        messages.warning(
            request, "Il n'y a aucun résultat avec ces termes. Essayez encore !"
        )
        GoToProduct = False

    context["GoToProduct"] = GoToProduct
    context["form_search"] = form

    return render(request, "home.html", context)

home/templates/layouts/_footer.html
 <!-- Footer-->

 <div class="pt-1 pb-1 footer page-footer" id="footer">
   <div class="text-center text-md-center mt-2">
     <div class="links">
       <div class="row">
         <div class="col-4 my-auto"><a href="{% url 'home:mentions' %}" title="Mentions Légales">Mentions
             Légales</i></a></div>
         <div class="text-center center-block align-middle col-4 my-auto">
           <a href="https://www.linkedin.com/in/aa061987/?originalSubdomain=fr" title="Linkedin"><i
               class="fa fa-linkedin fa-3x social social-link"></i></a>
           <a href="https://github.com/anselmia/P7.git" title="Github"><i
               class="fa fa-github-square fa-3x social social-gh"></i></a>
         </div>
         <div class="col-4 my-auto"><a href="/#contact" title="contact">Nous Contacter</i></a></div>
       </div>
     </div>
   </div>
 </div>

home/templates/layouts/_nav.html
{% load static %}

<nav class="navbar navbar-expand-lg navbar-light fixed-top py-3" id="mainNav">
    <div class="container-fluid">
        <a class="media-logo" href="{% url 'home:index' %}">
            <img class="main_logo" src="{% static 'images/logos/logo_fav.png' %}" style="border:0;" alt="Pur Beurre"
                width="70" height="50">
        </a>
        <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse"
            data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false"
            aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
            <ul class="navbar-nav ml-auto my-2 my-lg-0">
                {% if form_search.search %}
                <li class="nav-item searchbar_input">
                    <form action="{% url 'home:search' %}" method="POST" class="form-horizontal search">
                        {{ form_search.search.errors }}
                        <div class="searchbar">
                            {% csrf_token %}
                            {{ form_search.search }}
                            <input id="search-nav" type="submit" value="Go" class="search_icon search-button" />
                        </div>
                    </form>
                </li>
                {% endif %}
                <li class="nav-item text-center "><a class="nav-link js-scroll-trigger" title="home"
                        href="{% url 'home:index' %}" id="home"><i class="fas fa-home"></i><br>Acceuil</a></li>
                {% if user.is_authenticated %}
                <li class="nav-item text-center"><a class="nav-link js-scroll-trigger" title="Favoris"
                        href="{% url 'account:favorites' %}" id="favorites"><i class="fa fa-carrot"></i><br>Favoris</a>
                </li>
                <li class="nav-item text-center"><a class="nav-link js-scroll-trigger" title="Profile"
                        href="{% url 'account:profile' %}" id="profile"><i class="fa fa-user"
                            aria-hidden="true"></i><br>
                        {{user.username}}</a></li>
                <li class="nav-item text-center"><a class="nav-link js-scroll-trigger" title="Se déconnecter"
                        href="{% url 'account:logout' %}" id="logout"><i class="fa fa-sign-out fa-lg"
                            aria-hidden="true"></i><br>Se déconnecter</a></li>
                {% else %}
                <li class="nav-item text-center"><a class="nav-link js-scroll-trigger" title="Se connecter"
                        href="{% url 'account:login' %}" id="login"><i class="fa fa-user" aria-hidden="true"></i><br>
                        Se connecter</a></li>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>

home/templates/layouts/default.html
{% load static %}
<!DOCTYPE html>
<html lang="fr">

<head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
  <meta name="description" content="google maps bot place and history finder">
  <meta name="author" content="Arnaud Anselmi">

  {% if title %}
  <title>PurBeurre - {{ title }}</title>
  {% else %}
  <title>PurBeurre - Manger Malin !</title>
  {% endif %}

  <script src="https://kit.fontawesome.com/081751425d.js" crossorigin="anonymous"></script>
  <link rel="shortcut icon" href="https://addons.cdn.mozilla.net/favicon.ico">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
    integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  <link href="//netdna.bootstrapcdn .com/font-awesome/4.0.3/css/font-awesome.css" rel="stylesheet">
  <!-- Fotorama from CDNJS, 19 KB -->
  <link href="https://cdnjs.cloudflare.com/ajax/libs/fotorama/4.6.4/fotorama.css" rel="stylesheet">
  <link href="http://fonts.googleapis.com/css?family=Open+Sans" rel="stylesheet" type="text/css">
  <link href="http://fonts.googleapis.com/css?family=Open+Sans" rel="stylesheet" type="text/css">

  <link href="{% static 'css/styles.css' %}" rel="stylesheet">
  <link href="{% static 'css/search.css' %}" rel="stylesheet">
  <link href="{% static 'css/about.css' %}" rel="stylesheet">
  <link href="{% static 'css/nav.css' %}" rel="stylesheet">
  <link href="{% static 'css/pagination.css' %}" rel="stylesheet">
  <link href="{% static 'css/detail.css' %}" rel="stylesheet">
  <link href="{% static 'css/login.css' %}" rel="stylesheet">

  <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
  <link href="https://maxcdn.bootstrapcdn.com/js/ie10-viewport-bug-workaround.js">


</head>

<body id="page-top">
  {% include 'layouts/_nav.html'%}
  {% block body %}{% endblock %}
  <script type="text/javascript">
    Raven.config('https://4498abeb937f4dc2a38222e458ba61f5@o379406.ingest.sentry.io/5204212').install();
    window.onerror = Raven.process;
  </script>
  <script src="https://npmcdn.com/tether@1.2.4/dist/js/tether.min.js"></script>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
    integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous">
  </script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.bundle.min.js"></script>
  <!-- Third party plugin JS-->
  <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-easing/1.4.1/jquery.easing.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/magnific-popup.js/1.1.0/jquery.magnific-popup.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/fotorama/4.6.4/fotorama.js"></script>
  <script src="{% static 'js/scripts.js' %}"></script>
</body>

{% include 'layouts/_footer.html'%}

</html>